#!/bin/sh

uci set system.@system[0].hostname='beryl-ax-travel'

# Keep GL.iNet-like LAN addressing, useful when you are used to 192.168.8.1.
uci set network.lan.ipaddr='192.168.8.1'

uci commit system
uci commit network

exit 0
